language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "11"
install:
  - npm i -D mocha chai codecov istanbul
script:
  - npm test
  - npm run cov
notifications:
  email:
    on_success: change
    on_failure: always
